import react from '@vitejs/plugin-react-swc';
import { defineConfig } from 'vitest/config';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  base: '/project2',
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: 'src/test/setup.ts',
    mockReset: true,
    include: ['tests/**/*.test.tsx'],
    exclude: [
      './cypress',
      '**/node_modules/**',
      '**/dist/**',
      './src/main.tsx',
      './src/utils/**',
      '.tests/**',
      '.src/client/**',
    ],
    root: './',
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      reportsDirectory: 'tests/coverage',
      enabled: true,
      exclude: [
        'dist/**',
        'src/components/Pagination',
        'src/components/ProtectedRoute',
        'cypress',
        'src/vite-env.d.ts',
        'src/App.tsx',
        'src/components/subPages/**',
        'cypress.config.js',
        'eslint.config.js',
        'tailwind.config.js',
        'vite.config.mts',
        'src/hooks/**',
        'src/main.tsx',
        'src/utils/**',
        'src/pages/**',
        'src/interfaces/**',
        'src/graphql/**',
        'src/components/Toast/**',
        'tests/**',
        'src/client/apollo.ts',
        'postcss.config.cjs',
        'src/components/Layouts/**',
        'src/components/Home/**',
        'src/components/Navbar/**',
      ],
    },
  },
});
